title: "Kubernetes Türkçe"
logo: "/kaynaklar/kubernetes.png"
description: >  # this means to ignore newlines until "baseurl:"
  Kubernetes Türkçe başlangıç eğitimi ve temel içerikler.
baseurl: "/k8s-docs" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ibediko
github_username: edib

# Build settings
#theme: "just-the-docs"
remote_theme: "just-the-docs/just-the-docs"

toc:
    enabled: true
    h_min: 1
    h_max: 3


highlighter: rouge
syntax_highlighter_style: colorful


# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
mermaid: true
mermaid:
  path: "/asssets/js/mermaid-10.0.2.min.js"

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
    heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
    previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
    preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
    preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
    tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
    rel_url: true
    button: true


# Aux links for the upper right navigation
aux_links:
    "K8s Temel Eğitim on GitHub":
        - "//github.com/k8s-tr/k8s-docs/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false


# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true


footer_content: >
  '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
  <img alt="Creative Commons Lisansı" style="border-width:0"
   src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" />
  </a><br />Bu eser <a rel="license" 
  href="http://creativecommons.org/licenses/by-sa/4.0/">
  Creative Commons Atıf-AynıLisanslaPaylaş 4.0 Uluslararası Lisansı</a> ile lisanslanmıştır.'


last_edit_timestamp: true 
last_edit_time_format: "%b %e %Y at %I:%M %p" 

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "GitHub'ta düzenle."
gh_edit_repository: "https://github.com/k8s-tr/k8s-docs/" 
gh_edit_branch: "master" 
gh_edit_view_mode: "tree" 

include:
    - docs
